apiVersion: v1
kind: Service
metadata: 
  name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec: 
      containers: 
        - 
          image: nginx:v1